fixup! First pass at getting an mlinux-5 version to build

diff --git a/root/bitbake b/root/bitbake
--- a/root/bitbake
+++ b/root/bitbake
@@ -1,7 +1,5 @@
 #!/bin/bash -x
 
-set -x
-
 # Build environment must be passed
 test -n "${BUILD_DIR}" || exit $?
 cd ${BUILD_DIR} || exit $?
@@ -14,22 +12,20 @@ useradd -u ${BUILD_UID} -g ${BUILD_GROUP} ${BUILD_USER} || exit $?
 
 # Figure out what we are supposed to do
 if [ "${1}" == "--setup" ]; then
-    shift
     setuser ${BUILD_USER} bash -c ". ./setup.sh ${*}"
     exit $?
 fi
 
-rc=-1
+# Find and run our envivronment setup script
 for script in ./env-oe.sh ./oe-init-build-env; do
-    test -f ${script} || continue
-    setuser ${BUILD_USER} bash -c ". ${script}; bitbake ${*}"
-    rc=$?
-    break
+    if [ test -f ${script} ]; then
+	break
+    fi
 done
-
-if [ ${rc} -eq -1 ]; then
-    echo "Unable to find environment init script" >&2
-    rc=1
+if [ -z "${script}" ]; then
+    echo "Environment setup script not found" >&2
+    exit 1
 fi
 
-exit  $?
+setuser ${BUILD_USER} bash -c ". ${script}; bitbake ${*}"
+exit $?
